### ISSUE TITLE
Express Middlewares for Optimization

### ISSUE THREAD

**Issue by przekwas** [staceylaurel/dnd-ig-draft#1]
Install the following middlewares and their TS types, and add them as middlewares on your Express app!

- helmet @types/helmet
- compression @types/compression
- cors @types/cors

Add them as the first 3 middlewares on your Express app.

**Comment by przekwas** [comment]
Wait where do these go?

**Comment by staceylaurel** [comment]
okie dokie

**Comment by staceylaurel** [comment]
I think I did it right for cors. 
Cors was updated in server.ts ```app.use(require('cors')())```
I have pushed it so you can check.

**Comment by przekwas** [comment]
I showed you an example with cors in webinar on 2020-11-2 so do the same with the other middlewares.  Import the others I mention, and add them at the top of the express app's middleware list.
