### ISSUE TITLE
Add Database Models

### ISSUE THREAD

**Issue by przekwas** [staceylaurel/dnd-ig-draft#3]
Make a `src/server/db/models/index.ts` file

Make an interface for each table of your schema in this one file, for example:

```js
export interface BlogsModel {
  id?: number;
  title?: string;
  content?: string;
  created_at?: Date;
}
```

Each table should have a model, also make an export an interface for what we call the "canned response" of node mysql.

```js
{
  fieldCount: 0,
  affectedRows: 14,
  insertId: 0,
  serverStatus: 2,
  warningCount: 0,
  message: '\'Records:14  Duplicated: 0  Warnings: 0',
  protocol41: true,
  changedRows: 0
}
```
take that and make an interface out of it!

**Comment by staceylaurel** [comment]
![Screen Shot 2020-11-02 at 11 01 46 PM](https://user-images.githubusercontent.com/64053039/97951356-8b3c1000-1d5f-11eb-8f08-1997a0f158f6.png)

**Comment by przekwas** [comment]
Add them to all your queries as the appropriate return types
